### ISSUE TITLE
Release planning for version 2.3.1

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#233]
What do you think of releasing a version 2.3.1 soon? I think we already merged some nice fixes and with the recent problem of the removed `demime` in Exim 4.88 we risk to run into many complaints in the future (e.g. new Debian this year). We won't be able to do everything scheduled for 2.3.1, but I'd like to review your Mailman-fixes and also properly integrate a LMTP transport (without integration in web interface or database).
@rimas-kudelis

**Comment by rimas-kudelis** [comment]
We have so much issues and PR's marked for 2.3.1 that I'm not sure we can wrap it all up quickly.

On the other hand, if you think we've introduced enough changes to mandate a new release, I don't mind that. We can always retarget whatever doesn't make it into 2.3.1 and have another release later at some point.

**Comment by Udera** [comment]
Good. I will try to check what I can do in the next weeks. Everything else will be moved to the next release 2.3.2. I also hope to find an afternoon for vexim3.

**Comment by Udera** [comment]
I have reviewed a couple of PR, now I'd like to decide on those with the "to review" label:
https://github.com/vexim/vexim2/pulls?q=is%3Apr+is%3Aopen+label%3A%22to+review%22

After the merges we should do some testing and then push out vexim 2.3.1. Are there other things you want to get in?

**Comment by rimas-kudelis** [comment]
We have several long-standing code-related PR's (such as #106) which require more and more polishing with each commit we make, so in general, I'm in favor of reviewing and accepting as many of them as possible. However, as usual, I don't have enough free time (and perhaps even motivation) to actually review them properly, so I guess I'll leave these decisions up to you for now.

**Comment by Udera** [comment]
I already had a look into the LMTP transport (https://github.com/vexim/vexim2/pull/150), I wanted to do it differently but it didn't work out that easily (using the same router as we do currently). It's not a huge thing to implement but it would require some changes to the interface (which we suppose would be much easier on a newer interface).

Custom user names is really interesting (#106), at this point we could think about fiddling in LDAP support (or at least design it in a way that it is possible). The PR is rather small, we could give it a quick test and put it in. We risk to change it later.

All these spam-reducing stuff (#153, #161), I'm not really convinced of these solutions. We could put them into our wiki for people wanting to use it. We should review the anti-spam measures at some point, e.g. implementing something like policy.d but directly within exim (should be possible with ACLs to give "points" for certain features of a mail and reject them in the end if the total score exceeds a certain value).

**Comment by rimas-kudelis** [comment]
Re #150: I'd really like to avoid additional UI and DB changes, so I'd prefer LMTP to be a server-wide option for now. Furthermore, I'm not sure this is something a virtual domain administrator or even the end user should mingle with, so I guess I would have preferred it even if we were working on Vexim3.

Re #106: the use-case says it all, and assuming it's a small change as you say, I really don't think it would hurt for us to have it.

Regarding the other two: I'm too lame on the spam fighting front to weigh in on that. :) Although you made me wonder why you'd want to implement something directly in Exim when it is already implemented in another package.

**Comment by Udera** [comment]
I didn't have much time lately. I still think we should push vexim 2.3.1 a bit, some things which should go into it:

- [ ] Database issues: https://github.com/vexim/vexim2/issues/242
- [ ] Always accept postmaster mail: https://github.com/vexim/vexim2/issues/228, fix: https://github.com/vexim/vexim2/pull/248
- [ ] Postgres update scripts: https://github.com/vexim/vexim2/issues/196 https://github.com/vexim/vexim2/issues/244 (or move it to later??)

unsure (I don't use it, if someone finds the time to fix it would be great):

- [ ] specific Debian files: https://github.com/vexim/vexim2/issues/199, https://github.com/vexim/vexim2/issues/109

later (or if someone has time):

- [ ] local mailboxes: https://github.com/vexim/vexim2/issues/218
- [ ] User experience: https://github.com/vexim/vexim2/issues/162


Then, we can split off a vexim2.3 branch, and on master we can continue, implement some of the outstanding pull requests with new features. We can test them. Smaller things can be back-ported until vexim2.4 is considered stable enough.

@rimas-kudelis I hope you have some time to look into the mysql issues.

**Comment by VVD** [comment]
Is vexim alive?

**Comment by rimas-kudelis** [comment]
@VVD, it's not as active as we'd want it to be, but I wouldn't consider it completely dead either. More like, it's just pretty stale.

For more context, Vexim consists of three mostly independent parts, which can be stale or active mostly independently of each other:
1. Configuration snippets for MTAs and MDAs: may age over time, but we tend to update them as necessary.
2. Setup/update SQL scripts: only used once and basically don't age. However, each schema change/update make update/installation more complex, so I wanted to find a better way to maintain it.o
3. PHP front-end  for mailbox management: this is the really old and rusty part. We were hoping to replace it with a modern PHP frontend one day, but haven't done this so far. However, there is already an alternative frontend in Python (veximpy) available for it.

**Comment by VVD** [comment]
@rimas-kudelis, thanks for information.
1. Sorry for offtopic: found one bug in docs/debian-conf.d/router/250_vexim_virtual_domains - if user added in any group, then he can send emails in any closed group too - need `g.id = c.group_id`:
```
 virtual_dom_groups:
   driver = redirect
   domains = +local_domains
   allow_fail
   senders = ${if eq{Y}{${lookup mysql{select g.is_public \
                                       from groups g, domains d \
                                       where d.enabled = '1' and d.domain = '${quote_mysql:$domain}' and \
                                             d.domain_id = g.domain_id and g.enabled = '1' and \
                                             g.name = '${quote_mysql:$local_part}'}}} \
                  {$sender_address} \
                 {${lookup mysql{select concat_ws('@', u.localpart, d.domain) \
                                  from domains d, groups g, group_contents c, users u \
                                  where d.enabled = '1' and d.domain = '${quote_mysql:$domain}' and \
                                        d.domain_id = g.domain_id and g.name = '${quote_mysql:$local_part}' and \
-                                       g.enabled = '1' and \
+                                       g.enabled = '1' and g.id = c.group_id and \
                                        g.is_public = 'N' and c.member_id = u.user_id and \
                                       d.domain_id = u.domain_id and u.enabled = '1' \
                                       and u.username = '${quote_mysql:$sender_address}' limit 1}}}}
```
Plus extension - if added alias in non-public group, then sender from main login can send emails to group too:
```
virtual_dom_groups:
  driver = redirect
  domains = +local_domains
  allow_fail
  senders = ${if eq{Y}{${lookup mysql{select g.is_public \
                                      from groups g, domains d \
                                      where d.enabled = '1' and d.domain = '${quote_mysql:$domain}' and \
                                            d.domain_id = g.domain_id and g.enabled = '1' and \
                                            g.name = '${quote_mysql:$local_part}'}}} \
                 {$sender_address} \
                 {${lookup mysql{select concat_ws('@', u.localpart, d.domain) \
                                 from domains d, groups g, group_contents c, users u \
                                 where d.enabled = '1' and d.domain = '${quote_mysql:$domain}' and \
                                       d.domain_id = g.domain_id and g.name = '${quote_mysql:$local_part}' and \
                                       g.enabled = '1' and g.id = c.group_id and \
                                       g.is_public = 'N' and c.member_id = u.user_id and \
                                       d.domain_id = u.domain_id and u.enabled = '1' and \
                                       u.username = '${quote_mysql:$sender_address}' \
                                 union \
                                 select concat_ws('@', a.localpart, d.domain) \
                                 from domains d, groups g, group_contents c, users u, users a \
                                 where d.enabled = '1' and d.domain = '${quote_mysql:$domain}' and \
                                       d.domain_id = g.domain_id and g.name = '${quote_mysql:$local_part}' and \
                                       g.enabled = '1' and g.id = c.group_id and \
                                       g.is_public = 'N' and c.member_id = u.user_id and \
                                       d.domain_id = u.domain_id and u.enabled = '1' and a.enabled = 1 and \
                                       a.type = 'alias' and a.username = '${quote_mysql:$sender_address}' and \
                                       a.smtp = u.username }}}}
```
3. It isn't ready yet, doesn't support apache and etc. :-(

**Comment by runout-at** [comment]
@VVD cold you report bugs in an extra topic and provide a pull request please - don't hijack threads.

what do you mean with _It isn't ready yet, doesn't support apache and etc. :-(_ ? Vexim2 runs with Nginx, Apache, lighttp (I did test these) and for sure with many others.

**Comment by VVD** [comment]
> @VVD cold you report bugs in an extra topic and provide a pull request please - don't hijack threads.

Ok, I'll create new bug report, but without pull request.

> what do you mean with _It isn't ready yet, doesn't support apache and etc. :-(_ ? Vexim2 runs with Nginx, Apache, lighttp (I did test these) and for sure with many others.

It was answer on this suggestion:

> 3. PHP front-end for mailbox management: this is the really old and rusty part. We were hoping to replace it with a modern PHP frontend one day, but haven't done this so far. **However, there is already an alternative frontend in Python (veximpy) available for it**.

**Comment by VVD** [comment]
https://github.com/vexim/vexim2/issues/276

**Comment by VVD** [comment]
Please add patches from these issues to version 2.3.1 too:
https://github.com/vexim/vexim2/issues/279
https://github.com/vexim/vexim2/issues/281

**Comment by Udera** [comment]
> #281

this adds a new feature and changes the db-structure. I´d use a new version and not only a patch version.

**Comment by runout-at** [comment]
> > what do you mean with _It isn't ready yet, doesn't support apache and etc. :-(_ ? Vexim2 runs with Nginx, Apache, lighttp (I did test these) and for sure with many others.
> 
> It was answer on this suggestion:
> 
> > 3. PHP front-end for mailbox management: this is the really old and rusty part. We were hoping to replace it with a modern PHP frontend one day, but haven't done this so far. **However, there is already an alternative frontend in Python (veximpy) available for it**.

sorry for the delay...

Python does _not_ need a specific webserver. The python application runs on a WSGI (uwsgi, gunicorn, ...) or ASGI (hypercorn, uvicorn, ...) engine. For several reasons it makes sense to put a webserver in front of this engine. It's similar to php using php-fpm (or uwsgi) and put a webserver in front of it. In the old times Apache would have handled php itself but that had major drawbacks.

**Comment by VVD** [comment]
A larger zoo means more time for support and worse support.
I don't want to switch to something else, especially on python.

**Comment by vanzhiganov** [comment]
> > > what do you mean with _It isn't ready yet, doesn't support apache and etc. :-(_ ? Vexim2 runs with Nginx, Apache, lighttp (I did test these) and for sure with many others.
> > 
> > 
> > It was answer on this suggestion:
> > > 3. PHP front-end for mailbox management: this is the really old and rusty part. We were hoping to replace it with a modern PHP frontend one day, but haven't done this so far. **However, there is already an alternative frontend in Python (veximpy) available for it**.
> 
> sorry for the delay...
> 
> Python does _not_ need a specific webserver. The python application runs on a WSGI (uwsgi, gunicorn, ...) or ASGI (hypercorn, uvicorn, ...) engine. For several reasons it makes sense to put a webserver in front of this engine. It's similar to php using php-fpm (or uwsgi) and put a webserver in front of it. In the old times Apache would have handled php itself but that had major drawbacks.

Python is not good alternative for project with lack of development activity like Vexim. Because, a python packages have amount of incompatible updates from version to version.

**Comment by rimas-kudelis** [comment]
Each time there's some movement in this repository, I have this urge to rewrite Vexim using Symfony. But then I remind myself how little I use Vexim myself anymore, which translates directly into how little priority it has for me personally. So I just put it off, because meh, it's okay for me as it is.

But I do think that Vexim2's codebase is a dead-end. It's ugly and should be rewritten using modern practices before introducing any new functionality. **Especially** when such functionality involves database schema changes, because having a yet another non-versioned schema change would only grow the "zoo" of different Vexim DB schemas in use, which I'd like to avoid. Perhaps we should adopt an official policy about this?

As for the Python version, @runout-at did all the work there by himself, so I don't think any of use here is in the position to command him what technological choices to make.

**Comment by runout-at** [comment]
Thx. It was just my opinion but i think it's off topic here. If someone have the urge to discuss religious aspects of PHP vs Python - feel free to open a new Issue.

**Comment by Udera** [comment]
I didn't like the idea of changing the language either. However, if you use mailman, then you need python anyway.
My problem is, that I never done anything with webapps in python, so it needs some time to learn it. Just from looking at the code, I feel a bit lost 😨

**Comment by Udera** [comment]
> I'd specifically like to merge #264
I went over your PR quickly and it look ok so far.

> Anyone up for reviewing any PRs before the release?
I would switch my db on a working setup to utf8mb4 and then probably try a new install with this https://github.com/vexim/vexim2/pull/253.

> if we should tag 2.3.1
no tags at all? If we manage to test a bit, we will know at least that this version seems to work more or less and there are no conflicts or not too much inconsistencies between the merged PR.

**Comment by kaluang** [comment]
yes, afaik the mailman router does not work anymore starting Exim 4.96.

You have to add this line to mailman_router after line 517 in
"vexim2/docs/configure":
local_parts = dsearch,filter=dir;MAILMAN_HOME/lists

and in line 1049 in mailman_transport you have to change $local_part to
$local_part_data

(weirdly those lines do not work in my Exim 4.92, but I did not
investigate that further)

I did not come across other issues so far, but I also made several
changes to my exim4.conf over the years. So I have some significant
differences to "vexim2/docs/configure" in my current configuration.




Am 12.01.2024 um 14:08 schrieb runout-at:

**Comment by runout-at** [comment]
I'm going through my old PRs now. some are partly obsolete as functionality has been included into the default config (at least in Debian). So it' should be easier to include those features in Vexim. Shall we do this with this new release?

- #30 #245
- #246 #249
