### ISSUE TITLE
Code fixes to be done before testing/release of v2.3

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#94]
- [ ] Migration scripts: #59
- [x] Enable spamassassin for all addresses of a domain: #69 PR: #123 and #125
- [x] [Design]->display disabled accounts differently: #86, PR #96
- [x] Fix login when domain/account is disabled: #PR: #99
- [x] Make sure the e-mailaddress is RFC-conform: #108
- [x] Single Login-field: #110

these topics are still in discussion, they are not needed for some basic testing:
- [x] Update config-files: #8
- [ ] SSL-configuration: #45

@rimas-kudelis @Kami-no 

I just put together a list of open issues that need to be solved before the new release. It would be great to fix them as soon as possible in order to proceed with testing. Testing can be used to improve the documentation.

Anything else?

**Comment by rimas-kudelis** [comment]
[Look here](https://github.com/vexim/vexim2/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+2.3%22)

**Comment by Udera** [comment]
Yes, but some points are only about documentation. I thought it would be most reasonable, to handle the code issues first. Then we have an alpha-release which can be used for testing. So you can combine testing of the alpha release with updating the documentation.

**Comment by Udera** [comment]
How should we proceed once these topics are done? Create some sort of beta version and test on different systems (ask people via mailinglist to join the test)?

**Comment by rimas-kudelis** [comment]
Yep, I suppose so.

**Comment by Udera** [comment]
I started a wiki-entry for an overview of the testing procedure https://github.com/vexim/vexim2/wiki/Testing-for-vexim-2.3-release

**Comment by Udera** [comment]
The larger, inter-connected issues are solved. The rest is properly tagged with `version 2.3`. I'm closing here to get a clean bug tracker.
